version: "3.9"
name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    env_file: .env
    networks:
    - inception-network
    volumes:
      - /home/alefranc/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - /home/alefranc/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception-network
    volumes:
      - /home/alefranc/data/mysql:/var/lib/mysql
    restart: on-failure


networks:
  inception-network:
    name: inception-network
