version: "3.9"
name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    env_file: .env
    networks:
    - inception-network
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      - wordpress
    restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception-network
    volumes:
      - wp:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception-network
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', '/root/healthcheck.sh']
      interval: 10s
      timeout: 5s
      retries: 20
    restart: on-failure


networks:
  inception-network:
    name: inception-network

volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/alefranc/data/wordpress'
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/alefranc/data/wordpress'
