FROM alpine:3.17.0

RUN apk update
RUN apk add php php-fpm

# WORKDIR /app
# RUN wget https://wordpress.org/wordpress-6.1.1.tar.gz
# RUN tar -xzvf wordpress-6.1.1.tar.gz
# RUN rm -f wordpress-6.1.1.tar.gz
